### ISSUE TITLE
Command "shell" is not defined

### ISSUE THREAD

**Issue by borkweb** [moderntribe/tric#1]
With the recent changes [here](https://github.com/moderntribe/products-test-automation/commit/0d0667267d92c06bc53ac4ad0884a9e0cb41cb00#diff-c7a5795761cb3ccf96e703b46a482d1eL24), when I attempt to `tric shell`, I get the following:

![Screenshot from 2020-05-22 14-58-48](https://user-images.githubusercontent.com/430385/82700716-c2e54e80-9c3c-11ea-907b-5d548b422d91.png)

Note: this happens for the products-test-automation repo and this one.

**Comment by lucatume** [comment]
Did you run `tric update` to get the latest version of the containers?

**Comment by borkweb** [comment]
Worked like a champ. Thanks :D
