### ISSUE TITLE
Output message when using `xon` or `xoff`

### ISSUE THREAD

**Issue by cliffordp** [moderntribe/tric#48]
Suggested: `Xdebug has been enabled.` (or disabled) + the output of `php -v`

![image](https://user-images.githubusercontent.com/1812179/94027928-ff5abf80-fd80-11ea-9885-d4b1a0aaa89a.png)

**Comment by lucatume** [comment]
The output does not come from `tric`, but from the [the container it uses](https://hub.docker.com/repository/docker/lucatume/codeception); closing this as it's fixed there.
